version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery_worker
    volumes:
      - .:/app
    command: celery -A app.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"